/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ActionModal: typeof import('./src/components/Setting/component/ActionModal.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATree: typeof import('ant-design-vue/es')['Tree']
    ComponentAttr: typeof import('./src/components/Setting/component/ComponentAttr.vue')['default']
    ComponentEvent: typeof import('./src/components/Setting/component/ComponentEvent.vue')['default']
    ComponentStyle: typeof import('./src/components/Setting/component/ComponentStyle.vue')['default']
    EditArea: typeof import('./src/components/EditArea/index.vue')['default']
    GoToLink: typeof import('./src/components/Setting/actions/GoToLink.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HoverMask: typeof import('./src/components/HoverMask/index.vue')['default']
    LayoutItem: typeof import('./src/components/Setting/component/LayoutItem.vue')['default']
    Material: typeof import('./src/components/Material/index.vue')['default']
    MaterialItem: typeof import('./src/components/Material/MaterialItem.vue')['default']
    Outline: typeof import('./src/components/Material/Outline.vue')['default']
    Prview: typeof import('./src/components/Prview/index.vue')['default']
    RenderFormItem: typeof import('./src/components/Setting/component/RenderFormItem.vue')['default']
    SelectedMask: typeof import('./src/components/SelectedMask/index.vue')['default']
    Setting: typeof import('./src/components/Setting/index.vue')['default']
    Source: typeof import('./src/components/Material/Source.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
