/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ComponentAttr: typeof import('./src/components/Setting/component/ComponentAttr.vue')['default']
    ComponentEvent: typeof import('./src/components/Setting/component/ComponentEvent.vue')['default']
    ComponentStyle: typeof import('./src/components/Setting/component/ComponentStyle.vue')['default']
    CssEditor: typeof import('./src/components/Setting/component/CssEditor.vue')['default']
    EditArea: typeof import('./src/components/EditArea/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HoverMask: typeof import('./src/components/HoverMask/index.vue')['default']
    Material: typeof import('./src/components/Material/index.vue')['default']
    MaterialItem: typeof import('./src/components/Material/material-item.vue')['default']
    SelectedMask: typeof import('./src/components/SelectedMask/index.vue')['default']
    Setting: typeof import('./src/components/Setting/index.vue')['default']
  }
}
